import fs from 'fs/promises';
import fetchBooks from './fetchBooks'
// xml 生成には xml2js というライブラリを使っています
import { Builder } from 'xml2js';

try {
  const baseUrl = 'https://Tomohide-Kebukawa.github.io';

  // API にリクエスト
  const books = await fetchBooks();

  // xml に記述する URL のリスト作成
  const urls = books.map(({ keyword, id }) => ({
    loc: `${baseUrl}/ranking/${keyword}/book/${id}`
  }));

  // xml 生成
  const builder = new Builder();
  const sitemap = {
    urlset: {
      $: {
        xmlns: 'http://www.sitemaps.org/schemas/sitemap/0.9',
      },
      url: urls,
    },
  };
  const xml = builder.buildObject(sitemap);

  fs.writeFile('./public/sitemap.xml', xml);
} catch (e) {
  console.error(e);
  process.exit(1);
}
